// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjlhtyrwjhbnvzqdopam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqbGh0eXJ3amhibnZ6cWRvcGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTU5ODksImV4cCI6MjA3MTkzMTk4OX0.52bBH4TsU-uP_b7KYyOkDkakdrk1UdcFiZ0X9ihDAsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});